# Generated by Django 2.0.3 on 2018-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=30, unique=True, verbose_name='client email'),
            preserve_default=False,
        ),
    ]
