# Generated by Django 2.0.3 on 2018-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='buffer_time',
            field=models.PositiveIntegerField(default=1, verbose_name='Buffer time in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='minimum_booking',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum booking in hours'),
            preserve_default=False,
        ),
    ]
